### ISSUE TITLE
It's not working !

### ISSUE THREAD

**Issue by rsilvestre** [relax/relax#220]
I followed your install instruction 2 times from scratch.

0. install deps and config
  - brew uninstall homebrew/science/vips
  - git clone ...
  - npm install
  - create .relaxrc from .relaxrc.sample

1. dev mode

  - npm run dev
  - http://localhost:8080/admin/init
  - fill the form, click "let's get started" and Baam! ->

  request : 

  ```::1 - POST /graphql HTTP/1.1 400 125 - 5.104 ms```

  browser console error :

  ```
  Error: Bad Request
  (fonction anonyme)
  ```

2. prod mode

  - npm run build Baaam !

  ```
  $ npm run build

  > relax@0.0.0 build /Users/michaelsilvestre/git/relax
  > NODE_ENV=production ./node_modules/.bin/webpack --output-public-path public/js/ && cp -r assets/images/* public/images

  webpack 1.13.0
  Usage: https://webpack.github.io/docs/cli.html

  ...

  Output filename not configured.

  ...
  ```

Sade because the project look nice

**Comment by bruno12mota** [comment]
Hey! Relax is still not ready for production unfortunately. If you want to contribute or test it out locally, you should run:

```bash
npm run dev
```

instead of

```bash
npm run build
```

**Comment by Yaxian** [comment]
Hi , dear @bruno12mota ,
my node version is 4.4.1 and npm version is 2.14.20.
when i run `npm install`, the npm warns: 'history@1.17.0' react-router needs history@1.13.x. and no module 'source-map-supprot', and something else.
So sad that I can't start the server.
Does something wrong with package.json? Can you help me?

**Comment by Yaxian** [comment]
and the following errrs:

first is webpack error:
WARNING in ./lib/server/migrate.js
Critical dependencies:
37:18-64 the request of a dependency is an expression
 @ ./lib/server/migrate.js 37:18-64
 69% 1591/1606 build modulesexpress-session deprecated undefined resave option; provide resave option build/app.js:202:39
express-session deprecated undefined saveUninitialized option; provide saveUninitialized option build/app.js:202:39
 69% 1594/1607 build modulesdebug: Listening at port 8080
Hash: b77645b14460fb5966f0  
Version: webpack 1.13.0
Time: 11526ms
    Asset     Size  Chunks             Chunk Names
common.js  7.02 MB       0  [emitted]  common.js
 admin.js  2.47 MB       1  [emitted]  admin
  auth.js   320 kB       2  [emitted]  auth
public.js  1.42 kB       3  [emitted]  public
chunk    {0} common.js (common.js) 6.17 MB [rendered]
    [1] ./~/react/react.js 56 bytes {0} [built]
    [2] (webpack)/buildin/module.js 251 bytes {0} [built]
    [3] ./~/react-transform-catch-errors/lib/index.js 2.68 kB {0} [built]
    [4] ./~/react-transform-hmr/lib/index.js 3.69 kB {0} [built]
    [5] ./~/redbox-react/lib/index.js 8.25 kB {0} [built]
    [6] ./lib/shared/components/component.jsx 3.51 kB {0} [built]
    [7] ./~/css-loader/lib/css-base.js 1.51 kB {0} [built]
    [8] ./~/style-loader/addStyles.js 7.15 kB {0} [built]
    [9] (webpack)/~/node-libs-browser/~/process/browser.js 2.06 kB {0} [built]
   [10] ./~/moment/moment.js 122 kB {0} [built]
   [12] ./~/classnames/index.js 1.1 kB {0} [built]
   [14] ./~/lodash.foreach/index.js 2.4 kB {0} [built]
   [15] ./~/redux/lib/index.js 1.94 kB {0} [built]
   [16] ./~/react/~/fbjs/lib/invariant.js 1.51 kB {0} [built]
   [17] ./~/relate-js/dist/index.js 592 kB {0} [built]
   [19] (webpack)-dev-server/~/sockjs-client/~/inherits/inheri


second: in browser， when I create a new account:

Failed to load resource: the server responded with a status of 404 (Not Found)
[WDS] Hot Module Replacement enabled.
[HMR] Waiting for update signal from WDS...
 action @ 11:11:02.099 @@reduxReactRouter/initRoutes 
 prev state Object
 action Object
 next state Object
Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
 (client) <div class="index__conten
 (server) <div data-reactid=".1ul6g
SoundManager V2.97a.20150601 (HTML5-only mode)
SoundManager 2 HTML5 support: mp3 = true, mp4 = true, ogg = true, opus = true, wav = true
SoundManager 2: Ready. ✓
Failed to load resource: the server responded with a status of 404 (Not Found)
Failed to load resource: the server responded with a status of 404 (Not Found)
Failed to load resource: the server responded with a status of 404 (Not Found)
Failed to load resource: the server responded with a status of 404 (Not Found)
[WDS] Hot Module Replacement enabled.
Uncaught TypeError: Cannot convert undefined or null to object

**Comment by bruno12mota** [comment]
We recently made a huge refactor. Some things might be broken which we should fix soon. Some dependencies should be locked instead of using ^ as it is causing some unmet dependencies. Will go through them later on as well 👍

**Comment by bruno12mota** [comment]
Resolved the dependencies issue. Missing the init addUser one

**Comment by BoefAE** [comment]
Hi, the issue is still relevant. I just cloned and run `npm run dev` but I can't seem to register my first user. Same error as OP.

**Comment by Yaxian** [comment]
@BoefAE, you can visit `localhost:8080/admin/init` to register, but maybe it does'nt work, either. You can hack the passport validation by modify the `./lib/server/models/user.js` like:
```
passport.use(new Strategy((username, password, done) => {
  done(null, username)
}));
passport.serializeUser((username, done) => {
  done(null, username)
});
passport.deserializeUser((username, done) => {
  done(null, username)
});

```

and then visit `localhost:8080/admin/login`, type any thing. you can login

**Comment by BoefAE** [comment]
Thanks @Yaxian not a clean solution but at least I can use it

**Comment by bruno12mota** [comment]
I'll fix the init on thursday if no one does till then
